### ISSUE TITLE
Add support for SolusOS

### ISSUE THREAD

**Issue by BenStigsen** [smallstep/truststore#11]
All of the certificates on my Solus OS Linux system, seems to be in `/etc/ssl/certs/`, which as far as I can tell, does not get checked in the code.

In the `/etc/ssl/certs/` folder, pretty much every single certificate seems to be of the type `.pem`. 
There is however a single `.crt` called `ca-certificates.crt`

On Solus OS the `trust`and `tee` tool is also available.

**Comment by maraino** [comment]
Fixed with https://github.com/smallstep/truststore/pull/12
