### ISSUE TITLE
Continue even if a trust store is not found

### ISSUE THREAD

**Issue by mholt** [smallstep/truststore#3]
We [had an issue reported in Caddy](https://github.com/caddyserver/caddy/issues/3205) where Firefox was not installed, so installation into any other systems failed.

This error (and others like it for other trust stores) could be a sentinel value: https://github.com/smallstep/truststore/blob/33d81a51d1669f67d5feb8ec9189ee91876ed4e5/truststore_nss.go#L69

And then this error check: https://github.com/smallstep/truststore/blob/33d81a51d1669f67d5feb8ec9189ee91876ed4e5/truststore.go#L66

should account for that value, and `continue` (with a log probably) rather than `return err`.

In fact, perhaps installing into the system trust store should always be done first, rather than last...

**Comment by maraino** [comment]
Fixed with 903b41c208c1fab27284c1d75790a2cbf4df731e

**Comment by mholt** [comment]
Great, thanks!
